@startuml
actor 用户
skinparam sequenceMessageAlign center

用户 -> 订单系统: 提交订单

订单系统 -> 问诊系统: 补处方请求
问诊系统 --> 订单系统: 处方id

group 电子病历
...same minutes latter...
用户 -> 问诊系统: 补电子病历请求，处方id
问诊系统 -> 问诊系统: 补问诊记录
end
participant IM系统 #FFAAAA
问诊系统 -> IM系统: 分配聊天室
问诊系统 <-- IM系统: 聊天室信息

participant 分诊系统 #FFAAAA
问诊系统 -> 分诊系统: 处方信息，诊单信息，电子病历信息
note right
因用户提交电子病历信息与处方信息不同步
此时电子病历信息可能还未生成
end note
loop 10分钟
    分诊系统 ->分诊系统: 处方分配
    分诊系统 -> 医生工作台: 分配处方
end
note left #FFAAAA
自动生成的诊单如何分配？
现有分诊系统无法支持
现有处方分诊10分钟未审核会重新分配
end note

activate 医生

医生工作台 -> 医生: 处方信息
医生 <--[#000000]> 用户: 问诊在线沟通
destroy 医生
destroy 用户

医生工作台 <-- 医生: 保存病历，审核处方
医生 --> 订单系统: 处方审核通过
订单系统 ->仓库: 订单流转
仓库 --> 用户: 发货
医生 --[#0000FF]> 订单系统: 处方审核拒绝
订单系统--[#0000FF]> 用户: 退款


@enduml