@startuml
actor 用户
skinparam sequenceMessageAlign center

用户 -> 订单系统: 提交订单

订单系统 -> 问诊系统: 补处方请求
问诊系统 --> 订单系统: 处方id
问诊系统 -> 处方分诊: 处方信息
loop 3 分钟
    处方分诊 ->处方分诊: 处方分配
    处方分诊 -> 医生工作台: 分配处方
end

note left
3分诊医生未处理
处方会重新分配医生审核
end note
医生工作台 -> 医生: 处方信息
医生 --> 订单系统: 处方审核通过
订单系统 ->仓库: 订单流转
仓库 --> 用户: 发货
医生 --[#0000FF]> 订单系统: 处方审核拒绝
订单系统--[#0000FF]> 用户: 退货
@enduml