@startuml
(*) --> "下单"
if "是否包含冷链品" then
-->[false] "转DO"
--> "生成波次"
--> "拣货"
--> "装箱"
--> "核对出库单"
--> "交接"
--> "快递揽收"
-right-> (*)
else
->[true] "拆单"  #99FF99
--> ===B1===
note right #99FF99
拆单逻辑
end note
-->[根据药品拆单] "常温"

--> "正常转DO"
--> ===B2===
===B1=== -right-> "冷链订单" #99FF99
--> ===B2===
--> "审核发货" #99FF99
if  "是否通过"  then
note right #99FF99
审核记录保存
end note

-->[true] "保存审核记录" #99FF99
--> "调用顺丰接口下单"  #99FF99
--> "通知WMS修改承运商并出库"  #99FF99
-right-> (*)
else
-left->[false] (*)


@enduml