@startuml
start

fork
:用户提交问诊;
:分诊系统;
fork again
:医生上线接诊;
detach
end fork
:分配到诊单|
partition 问诊基本信息查询 {
    :查询病历模板列表 |
    :查询患者就诊记录|
    :查询患者电子病历记录|
    :查询患者处方记录|
}
while (问诊进行中?) is (病情沟通)
fork
:IM系统 |
fork again
if (聊天信息填入病历) then (yes)
:聊天信息填入病历 <
elseif (病历模板选择) then (yes)
:病历模板选择 <
elseif (病历字段模板选择) then (yes)
:病历字段模板选择 <
endif
:主诉快捷输入 <
:过敏史字典选择 <
:ICD10诊断选择 <

:病历保存;

:开处方操作 >
:ICD10诊断选择 <
if (处方模板选择) then (yes)
:处方模板选择 <
elseif (药品搜索) then (yes)
while (药品搜索) is (药品数量小于5？)
:添加药品 <
:填写用法用量 <
:药品数量填写 <
endwhile (药品数量大于5)
endif
partition 处方检查 {
:药品配伍禁忌检查 <
:药品缺货检查 <
}
:开具处方;
:CA签章 |

end fork
endwhile (病历处方填写完成)

:药师审方 |
note right
审方目前为自动审核
end note

:处方推送至用户;
:用户凭处方购药;
note right
后续为诊后流程
end note
stop
@enduml